labels: [rfc]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        An abstract, tl;dr, or executive summary of your RFC.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: |
        Describe the problem your RFC is trying to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Describe your proposal, with a focus on clarity of meaning. You MAY use [RFC2119-style](https://www.ietf.org/rfc/rfc2119.txt) MUST, SHOULD and MAY language to help clarify your intentions.
    validations:
      required: true